name: UhcMain
version: "1.0"
author: Arnau
main: me.arnaumas.UhcMain
description: prova eclipse
api-version: 1.16

commands:
  teams:
    description: comando teams
  skull:
    description: obtenir caps de jugadors
